[workspace]
authors = ["ShriSuha <suhasinivenkatesh.official@gmail.com>"]
channels = ["conda-forge"]
name = "pkoffee"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
scipy = ">=1.17.0,<2"
seaborn = ">=0.13.2,<0.14"

[feature.dev.dependencies]
jupyterlab = "*"

[environments]
default = { features = ["default", "dev"], solve-group = "prod-group" }
prod = { features = ["default"], solve-group = "prod-group" }


