
[workspace]
authors = ["Hana Ali Messaoud <hana.alimessaoud@lapp.in2p3.fr>"]
channels = ["conda-forge"]
name = "pkoffee"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"
preview = ['pixi-build']

[package]
name = "pkoffee"
[package.build]
backend = { name = "pixi-build-python", version = ">=0.4.1,<5.0.0" }

[package.build.config]

[package.build-dependencies]

[package.host-dependencies]
# pixi build back-end calls uv or pip with "no-build-isolation" so build tools need to be available
# setuptools and other build tools should be host dependencies for now, see https://pixi.sh/latest/build/dependency_types/#python-code
uv = ">=0.9.9,<0.10.0"
uv-build = ">=0.9.9,<0.10.0"

[package.run-dependencies]
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
scipy = ">=1.17.0,<2"
seaborn = ">=0.13.2,<0.14"


[tasks]
# [package.build.backend]
# name = "pixi-build-python"
# version = "0.4.*"


[dependencies]

# Source - https://stackoverflow.com/apython = ">=3.14.2,<3.15"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
scipy = ">=1.17.0,<2"
seaborn = ">=0.13.2,<0.14"
pkoffee = { path = "." }
pyyaml = ">=6.0,<7"
# Posted by illusionx
# Retrieved 2026-01-15, License - CC BY-SA 4.0


[feature.py312.dependencies]
python = ">=3.12,<3.13"

[feature.py313.dependencies]
python = ">=3.13,<3.14"

[feature.py314.dependencies]
python = ">=3.14,<3.15"

[feature.dev.dependencies]
jupyterlab = "*"
